theme: olive
locale: en

msgs_per_page: 20
msgs_refresh_time: 300
msgs_send_type: html
msgs_update_time: 300

msg_subject_length: 45

imap_debug: true
imap_use_ssl: 'false'
imap_port: 143
imap_ssl_port: 993
imap_bye_timeout_retry_seconds: 2
imap_fetch_slice: 20

session_encryption: true
session_password: asDD3s2@sAdc983#

mailbox_max_parent_folder_depth: 3
mailbox_inbox: INBOX
mailbox_trash: Trash
mailbox_sent: Sent
mailbox_drafts: Drafts

